### ISSUE TITLE
Question when run the org.gvsig.landregistryviewer.main.Main

### ISSUE THREAD

**Issue by Hanyuxin** [moovida/gvsig-sample#1]
Hello!

When I run this program, several errors appear, and it can not run successfully.  Do you guys have any 

idea about what lead to these errors? I will list the problem in the following.

Thank you!

Jenny

16:16:34,286 INFO  [locator.AbstractLocator.get()]
  Can't locate class of 'dal.swing.manager', may be it is not registered in this locator 'dal.swing.locator'.
16:16:34,286 INFO  [swing.DALSwingLibrary.postInitialize()]
  Can't postinitialize library 'org.gvsig.fmap.dal.swing.DALSwingLibrary'.
A Class or Factory has not been registered for the reference dal.swing.manager in the Locator dal.swing.locator
	at org.gvsig.tools.locator.AbstractLocator.get(AbstractLocator.java:66)
	at org.gvsig.fmap.dal.swing.DALSwingLocator.getSwingManager(DALSwingLocator.java:89)
	at org.gvsig.fmap.dal.swing.DALSwingLibrary.doPostInitialize(DALSwingLibrary.java:51)
	at org.gvsig.tools.library.AbstractLibrary.postInitialize(AbstractLibrary.java:358)
	at org.gvsig.tools.library.AbstractLibrariesInitializer.initializeLibraries(AbstractLibrariesInitializer.java:252)
	at org.gvsig.tools.library.AbstractLibrariesInitializer.postInitialize(AbstractLibrariesInitializer.java:105)
	at org.gvsig.tools.library.AbstractLibrariesInitializer.postInitialize(AbstractLibrariesInitializer.java:95)
	at org.gvsig.tools.library.AbstractLibrariesInitializer.fullInitialize(AbstractLibrariesInitializer.java:111)
	at org.gvsig.landregistryviewer.main.Main.main(Main.java:90)

16:16:34,747 INFO  [locator.AbstractLocator.get()]
  Can't locate class of 'default.layer.order.manager', may be it is not registered in this locator 'org.gvsig.fmap.mapcontext.MapContextLocator'.
16:16:34,747 INFO  [mapcontext.MapContextLocator.getDefaultOrderManager()]
  Cant get default layer order manager
A Class or Factory has not been registered for the reference default.layer.order.manager in the Locator org.gvsig.fmap.mapcontext.MapContextLocator
	at org.gvsig.tools.locator.AbstractLocator.get(AbstractLocator.java:66)
	at org.gvsig.fmap.mapcontext.MapContextLocator.getDefaultOrderManager(MapContextLocator.java:201)
	at org.gvsig.fmap.mapcontext.MapContext.getOrderManager(MapContext.java:1822)
	at org.gvsig.fmap.mapcontext.layers.FLayers.addLayer(FLayers.java:190)
	at org.gvsig.fmap.mapcontext.layers.FLayers.add(FLayers.java:1217)
	at org.gvsig.landregistryviewer.main.Main.initMapControl(Main.java:184)
	at org.gvsig.landregistryviewer.main.Main.doMain(Main.java:240)
	at org.gvsig.landregistryviewer.main.Main.main(Main.java:92)
Exception in thread "main" java.lang.NullPointerException
	at org.gvsig.fmap.mapcontext.layers.FLayers.addLayer(FLayers.java:190)
	at org.gvsig.fmap.mapcontext.layers.FLayers.add(FLayers.java:1217)
	at org.gvsig.landregistryviewer.main.Main.initMapControl(Main.java:184)
	at org.gvsig.landregistryviewer.main.Main.doMain(Main.java:240)
	at org.gvsig.landregistryviewer.main.Main.main(Main.java:92)

**Comment by moovida** [comment]
Hi @Hanyuxin are you trying to compile this with gvSIG 2.3.x? And does this error occur when using the plugins as they are or did you change them?

If there is an error in the example, I want to fix it.
